<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Odin</string>
        <key>scopeName</key>
        <string>source.odin</string>
        <key>fileTypes</key>
        <array>
            <string>odin</string>
        </array>
        <key>firstLineMatch</key>
        <string>(?i)-[*]-\s*(mode:)?\s*odin\s*-[*]-</string>
        <key>uuid</key>
        <string>d94cbd06-b698-4935-b65c-501eb3e1e0b0</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#types</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#keywords</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#functions_and_declarations</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#strings</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>block_comment</key>
            <dict>
                <key>name</key>
                <string>comment.block.odin</string>
                <key>begin</key>
                <string>/\*</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.odin</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\*/</string>
            </dict>

            <key>line_comment</key>
            <dict>
                <key>begin</key>
                <string>(^[ \t]+)?((?=//)|(?=#!))</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.whitespace.comment.leading.odin</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(?!\G)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>//</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.odin</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>(?=\n)</string>
                        <key>name</key>
                        <string>comment.line.double-slash.odin</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>match</key>
                                <string>(?&gt;\\\s*\n)</string>
                                <key>name</key>
                                <string>punctuation.separator.continuation.odin</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>#!</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.odin</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>(?=\n)</string>
                        <key>name</key>
                        <string>comment.line.double-slash.odin</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>match</key>
                                <string>(?&gt;\\\s*\n)</string>
                                <key>name</key>
                                <string>punctuation.separator.continuation.odin</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>

            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#block_comment</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\*/.*\n</string>
                        <key>name</key>
                        <string>invalid.illegal.stray-comment-end.odin</string>
                    </dict>

                    <dict>
                        <key>include</key>
                        <string>#line_comment</string>
                    </dict>
                </array>
            </dict>
            <key>keywords</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\b(import|foreign|package)\b</string>
                        <key>name</key>
                        <string>keyword.control.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(if|else|when|for|in|not_in|defer|switch|return|const|do|where)\b</string>
                        <key>name</key>
                        <string>keyword.control.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(fallthrough|break|continue|case)\b</string>
                        <key>name</key>
                        <string>keyword.control.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(using)\b</string>
                        <key>name</key>
                        <string>keyword.control.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(asm|or_return|or_else|or_break|or_continue)\b</string>
                        <key>name</key>
                        <string>keyword.control.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(distinct)\b</string>
                        <key>name</key>
                        <string>keyword.operator.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(context)\b</string>
                        <key>name</key>
                        <string>keyword.operator.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(nil|true|false)\b</string>
                        <key>name</key>
                        <string>constant.language.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(\d(\d|_)*(\.\d(\d|_)*)?)((e|E)(\+|-)?\d+)?[ijk]?\b</string>
                        <key>name</key>
                        <string>constant.numeric.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b((0b(0|1|_)+)|(0o(\d|_)+)|(0d(\d|_)+)|(0[xXh](\h|_)+))[ijk]?\b</string>
                        <key>name</key>
                        <string>constant.numeric.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>---</string>
                        <key>name</key>
                        <string>constant.numeric.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(struct|enum|union|map|bit_set|bit_field|dynamic)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(cast|transmute|auto_cast)\b</string>
                        <key>name</key>
                        <string>keyword.function.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>([#]\s*\b([[:alpha:]_]+[[:alnum:]_]*)\b)</string>
                        <key>name</key>
                        <string>keyword.tag.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(#[+]\s*[[:alpha:]-][[:alnum:]-]*)</string>
                        <key>name</key>
                        <string>keyword.tag.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\x40\s*\b([[:alpha:]_]+[[:alnum:]_]*)\b)</string>
                        <key>name</key>
                        <string>keyword.tag.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\x40\s*[(]\s*\b([[:alpha:]_]+[[:alnum:]_]*)\b)\s*[)]</string>
                        <key>name</key>
                        <string>keyword.tag.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>@</string>
                        <key>name</key>
                        <string>keyword.operator.odin</string>
                    </dict>
                </array>
            </dict>
            <key>types</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\b(struct|enum|union|bit_field|bit_set)\b(?:(\{)(\}))?</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(proc)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\$\s*(\b([[:alpha:]_]+[[:alnum:]_]*)\b)</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <!-- Basic Types -->
                    <dict>
                        <key>match</key>
                        <string>\b(i8|i16|i32|i64|i128|int)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(u8|u16|u32|u64|u128|uint|uintptr)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(f16|f32|f64|f128)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(f16le|f32le|f64le|f128le)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(f16be|f32be|f64be|f128be)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(complex32|complex64|complex128)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(quaternion64|quaternion128|quaternion256)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(bool|b8|b16|b32|b64)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(string|cstring|rune)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(rawptr)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(any|typeid)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(byte)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(u16le|u32le|u64le|u128le|i16le|i32le|i64le|i128le)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(i16be|i32be|i64be|i128be|u16be|u32be|u64be|u128be)\b</string>
                        <key>name</key>
                        <string>storage.type.odin</string>
                    </dict>
                </array>
            </dict>
            <key>functions_and_declarations</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*(proc)</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>meta.function.odin entity.name.function.odin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*([#]force_inline|[#]force_no_inline)\s+(proc)</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>meta.function.odin entity.name.function.odin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.control.odin</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(proc)\s*[\(]</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[!]?\s*[\(]</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>support.function.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*(struct|union|enum|bit_field|bit_set)</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>meta.type.odin entity.name.type.odin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*([#]\s*type)</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>meta.type.odin entity.name.type.odin</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.tag.odin</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>meta.constant.odin entity.name.type.odin</string>
                            </dict>
                        </dict>
                    </dict>
                </array>
            </dict>
            <key>string_escaped_char</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\\(\\|[abefnrutv'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
                        <key>name</key>
                        <string>constant.character.escape.odin</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\\.</string>
                        <key>name</key>
                        <string>invalid.illegal.unknown-escape.odin</string>
                    </dict>
                </array>
            </dict>
            <key>strings</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.odin</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>"</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.odin</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.double.odin</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#string_placeholder</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#string_escaped_char</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>'</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.odin</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>'</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.odin</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.single.odin</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#string_escaped_char</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>`</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.odin</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>`</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.odin</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.raw.odin</string>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>
